// automatically generated by the FlatBuffers compiler, do not modify

package com.aliyun.igraph.client.proto.gremlin_fb;

import com.google.flatbuffers.FlatBufferBuilder;
import com.google.flatbuffers.Table;

import java.nio.ByteBuffer;
import java.nio.ByteOrder;

/**
 * @author alibaba
 */
@SuppressWarnings("unused")
public final class BoolValue extends Table {
  public static BoolValue getRootAsBoolValue(ByteBuffer _bb) { return getRootAsBoolValue(_bb, new BoolValue()); }
  public static BoolValue getRootAsBoolValue(ByteBuffer _bb, BoolValue obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__init(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public BoolValue __init(int _i, ByteBuffer _bb) { bb_pos = _i; bb = _bb; return this; }

  public boolean value() { int o = __offset(4); return o != 0 ? 0!=bb.get(o + bb_pos) : false; }

  public static int createBoolValue(FlatBufferBuilder builder,
      boolean value) {
    builder.startObject(1);
    BoolValue.addValue(builder, value);
    return BoolValue.endBoolValue(builder);
  }

  public static void startBoolValue(FlatBufferBuilder builder) { builder.startObject(1); }
  public static void addValue(FlatBufferBuilder builder, boolean value) { builder.addBoolean(0, value, false); }
  public static int endBoolValue(FlatBufferBuilder builder) {
    int o = builder.endObject();
    return o;
  }
}

