// automatically generated by the FlatBuffers compiler, do not modify

package com.aliyun.igraph.client.proto.gremlin_fb;

import com.google.flatbuffers.FlatBufferBuilder;
import com.google.flatbuffers.Table;

import java.nio.ByteBuffer;
import java.nio.ByteOrder;

/**
 * @author alibaba
 */
@SuppressWarnings("unused")
public final class DoubleValue extends Table {
  public static DoubleValue getRootAsDoubleValue(ByteBuffer _bb) { return getRootAsDoubleValue(_bb, new DoubleValue()); }
  public static DoubleValue getRootAsDoubleValue(ByteBuffer _bb, DoubleValue obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__init(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public DoubleValue __init(int _i, ByteBuffer _bb) { bb_pos = _i; bb = _bb; return this; }

  public double value() { int o = __offset(4); return o != 0 ? bb.getDouble(o + bb_pos) : 0.0; }

  public static int createDoubleValue(FlatBufferBuilder builder,
      double value) {
    builder.startObject(1);
    DoubleValue.addValue(builder, value);
    return DoubleValue.endDoubleValue(builder);
  }

  public static void startDoubleValue(FlatBufferBuilder builder) { builder.startObject(1); }
  public static void addValue(FlatBufferBuilder builder, double value) { builder.addDouble(0, value, 0.0); }
  public static int endDoubleValue(FlatBufferBuilder builder) {
    int o = builder.endObject();
    return o;
  }
}

