// automatically generated by the FlatBuffers compiler, do not modify

package com.aliyun.igraph.client.proto.gremlin_fb;

import com.google.flatbuffers.FlatBufferBuilder;
import com.google.flatbuffers.Table;

import java.nio.ByteBuffer;
import java.nio.ByteOrder;

/**
 * @author alibaba
 */
@SuppressWarnings("unused")
public final class ErrorInfo extends Table {
  public static ErrorInfo getRootAsErrorInfo(ByteBuffer _bb) { return getRootAsErrorInfo(_bb, new ErrorInfo()); }
  public static ErrorInfo getRootAsErrorInfo(ByteBuffer _bb, ErrorInfo obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__init(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public ErrorInfo __init(int _i, ByteBuffer _bb) { bb_pos = _i; bb = _bb; return this; }

  public long errorCode() { int o = __offset(4); return o != 0 ? (long)bb.getInt(o + bb_pos) & 0xFFFFFFFFL : 0; }
  public String errorMessage() { int o = __offset(6); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer errorMessageAsByteBuffer() { return __vector_as_bytebuffer(6, 1); }

  public static int createErrorInfo(FlatBufferBuilder builder,
      long error_code,
      int error_messageOffset) {
    builder.startObject(2);
    ErrorInfo.addErrorMessage(builder, error_messageOffset);
    ErrorInfo.addErrorCode(builder, error_code);
    return ErrorInfo.endErrorInfo(builder);
  }

  public static void startErrorInfo(FlatBufferBuilder builder) { builder.startObject(2); }
  public static void addErrorCode(FlatBufferBuilder builder, long errorCode) { builder.addInt(0, (int)errorCode, 0); }
  public static void addErrorMessage(FlatBufferBuilder builder, int errorMessageOffset) { builder.addOffset(1, errorMessageOffset, 0); }
  public static int endErrorInfo(FlatBufferBuilder builder) {
    int o = builder.endObject();
    return o;
  }
}

