// automatically generated by the FlatBuffers compiler, do not modify

package com.aliyun.igraph.client.proto.gremlin_fb;

import com.google.flatbuffers.FlatBufferBuilder;
import com.google.flatbuffers.Table;

import java.nio.ByteBuffer;
import java.nio.ByteOrder;

/**
 * @author alibaba
 */
@SuppressWarnings("unused")
public final class Int16ValueColumn extends Table {
  public static Int16ValueColumn getRootAsInt16ValueColumn(ByteBuffer _bb) { return getRootAsInt16ValueColumn(_bb, new Int16ValueColumn()); }
  public static Int16ValueColumn getRootAsInt16ValueColumn(ByteBuffer _bb, Int16ValueColumn obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__init(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public Int16ValueColumn __init(int _i, ByteBuffer _bb) { bb_pos = _i; bb = _bb; return this; }

  public short value(int j) { int o = __offset(4); return o != 0 ? bb.getShort(__vector(o) + j * 2) : 0; }
  public int valueLength() { int o = __offset(4); return o != 0 ? __vector_len(o) : 0; }
  public ByteBuffer valueAsByteBuffer() { return __vector_as_bytebuffer(4, 2); }

  public static int createInt16ValueColumn(FlatBufferBuilder builder,
      int valueOffset) {
    builder.startObject(1);
    Int16ValueColumn.addValue(builder, valueOffset);
    return Int16ValueColumn.endInt16ValueColumn(builder);
  }

  public static void startInt16ValueColumn(FlatBufferBuilder builder) { builder.startObject(1); }
  public static void addValue(FlatBufferBuilder builder, int valueOffset) { builder.addOffset(0, valueOffset, 0); }
  public static int createValueVector(FlatBufferBuilder builder, short[] data) { builder.startVector(2, data.length, 2); for (int i = data.length - 1; i >= 0; i--) builder.addShort(data[i]); return builder.endVector(); }
  public static void startValueVector(FlatBufferBuilder builder, int numElems) { builder.startVector(2, numElems, 2); }
  public static int endInt16ValueColumn(FlatBufferBuilder builder) {
    int o = builder.endObject();
    return o;
  }
}

