// automatically generated by the FlatBuffers compiler, do not modify

package com.aliyun.igraph.client.proto.gremlin_fb;

import com.google.flatbuffers.FlatBufferBuilder;
import com.google.flatbuffers.Table;

import java.nio.ByteBuffer;
import java.nio.ByteOrder;

/**
 * @author alibaba
 */
@SuppressWarnings("unused")
public final class Int16Value extends Table {
  public static Int16Value getRootAsInt16Value(ByteBuffer _bb) { return getRootAsInt16Value(_bb, new Int16Value()); }
  public static Int16Value getRootAsInt16Value(ByteBuffer _bb, Int16Value obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__init(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public Int16Value __init(int _i, ByteBuffer _bb) { bb_pos = _i; bb = _bb; return this; }

  public short value() { int o = __offset(4); return o != 0 ? bb.getShort(o + bb_pos) : 0; }

  public static int createInt16Value(FlatBufferBuilder builder,
      short value) {
    builder.startObject(1);
    Int16Value.addValue(builder, value);
    return Int16Value.endInt16Value(builder);
  }

  public static void startInt16Value(FlatBufferBuilder builder) { builder.startObject(1); }
  public static void addValue(FlatBufferBuilder builder, short value) { builder.addShort(0, value, 0); }
  public static int endInt16Value(FlatBufferBuilder builder) {
    int o = builder.endObject();
    return o;
  }
}

