// automatically generated by the FlatBuffers compiler, do not modify

package com.aliyun.igraph.client.proto.gremlin_fb;

import com.google.flatbuffers.FlatBufferBuilder;
import com.google.flatbuffers.Table;

import java.nio.ByteBuffer;
import java.nio.ByteOrder;

/**
 * @author alibaba
 */
@SuppressWarnings("unused")
public final class Int64Value extends Table {
  public static Int64Value getRootAsInt64Value(ByteBuffer _bb) { return getRootAsInt64Value(_bb, new Int64Value()); }
  public static Int64Value getRootAsInt64Value(ByteBuffer _bb, Int64Value obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__init(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public Int64Value __init(int _i, ByteBuffer _bb) { bb_pos = _i; bb = _bb; return this; }

  public long value() { int o = __offset(4); return o != 0 ? bb.getLong(o + bb_pos) : 0; }

  public static int createInt64Value(FlatBufferBuilder builder,
      long value) {
    builder.startObject(1);
    Int64Value.addValue(builder, value);
    return Int64Value.endInt64Value(builder);
  }

  public static void startInt64Value(FlatBufferBuilder builder) { builder.startObject(1); }
  public static void addValue(FlatBufferBuilder builder, long value) { builder.addLong(0, value, 0); }
  public static int endInt64Value(FlatBufferBuilder builder) {
    int o = builder.endObject();
    return o;
  }
}

