// automatically generated by the FlatBuffers compiler, do not modify

package com.aliyun.igraph.client.proto.gremlin_fb;

import com.google.flatbuffers.FlatBufferBuilder;
import com.google.flatbuffers.Table;

import java.nio.ByteBuffer;
import java.nio.ByteOrder;

/**
 * @author alibaba
 */
@SuppressWarnings("unused")
public final class Int8Value extends Table {
  public static Int8Value getRootAsInt8Value(ByteBuffer _bb) { return getRootAsInt8Value(_bb, new Int8Value()); }
  public static Int8Value getRootAsInt8Value(ByteBuffer _bb, Int8Value obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__init(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public Int8Value __init(int _i, ByteBuffer _bb) { bb_pos = _i; bb = _bb; return this; }

  public byte value() { int o = __offset(4); return o != 0 ? bb.get(o + bb_pos) : 0; }

  public static int createInt8Value(FlatBufferBuilder builder,
      byte value) {
    builder.startObject(1);
    Int8Value.addValue(builder, value);
    return Int8Value.endInt8Value(builder);
  }

  public static void startInt8Value(FlatBufferBuilder builder) { builder.startObject(1); }
  public static void addValue(FlatBufferBuilder builder, byte value) { builder.addByte(0, value, 0); }
  public static int endInt8Value(FlatBufferBuilder builder) {
    int o = builder.endObject();
    return o;
  }
}

