// automatically generated by the FlatBuffers compiler, do not modify

package com.aliyun.igraph.client.proto.gremlin_fb;

import com.google.flatbuffers.FlatBufferBuilder;
import com.google.flatbuffers.Table;

import java.nio.ByteBuffer;
import java.nio.ByteOrder;

/**
 * @author alibaba
 */
@SuppressWarnings("unused")
public final class MultiErrorInfo extends Table {
  public static MultiErrorInfo getRootAsMultiErrorInfo(ByteBuffer _bb) { return getRootAsMultiErrorInfo(_bb, new MultiErrorInfo()); }
  public static MultiErrorInfo getRootAsMultiErrorInfo(ByteBuffer _bb, MultiErrorInfo obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__init(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public MultiErrorInfo __init(int _i, ByteBuffer _bb) { bb_pos = _i; bb = _bb; return this; }

  public ErrorInfo errorInfo(int j) { return errorInfo(new ErrorInfo(), j); }
  public ErrorInfo errorInfo(ErrorInfo obj, int j) { int o = __offset(4); return o != 0 ? obj.__init(__indirect(__vector(o) + j * 4), bb) : null; }
  public int errorInfoLength() { int o = __offset(4); return o != 0 ? __vector_len(o) : 0; }

  public static int createMultiErrorInfo(FlatBufferBuilder builder,
      int error_infoOffset) {
    builder.startObject(1);
    MultiErrorInfo.addErrorInfo(builder, error_infoOffset);
    return MultiErrorInfo.endMultiErrorInfo(builder);
  }

  public static void startMultiErrorInfo(FlatBufferBuilder builder) { builder.startObject(1); }
  public static void addErrorInfo(FlatBufferBuilder builder, int errorInfoOffset) { builder.addOffset(0, errorInfoOffset, 0); }
  public static int createErrorInfoVector(FlatBufferBuilder builder, int[] data) { builder.startVector(4, data.length, 4); for (int i = data.length - 1; i >= 0; i--) builder.addOffset(data[i]); return builder.endVector(); }
  public static void startErrorInfoVector(FlatBufferBuilder builder, int numElems) { builder.startVector(4, numElems, 4); }
  public static int endMultiErrorInfo(FlatBufferBuilder builder) {
    int o = builder.endObject();
    return o;
  }
}

