// automatically generated by the FlatBuffers compiler, do not modify

package com.aliyun.igraph.client.proto.gremlin_fb;

import com.google.flatbuffers.FlatBufferBuilder;
import com.google.flatbuffers.Table;

import java.nio.ByteBuffer;
import java.nio.ByteOrder;

/**
 * @author alibaba
 */
@SuppressWarnings("unused")
public final class MultiStringValueColumn extends Table {
  public static MultiStringValueColumn getRootAsMultiStringValueColumn(ByteBuffer _bb) { return getRootAsMultiStringValueColumn(_bb, new MultiStringValueColumn()); }
  public static MultiStringValueColumn getRootAsMultiStringValueColumn(ByteBuffer _bb, MultiStringValueColumn obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__init(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public MultiStringValueColumn __init(int _i, ByteBuffer _bb) { bb_pos = _i; bb = _bb; return this; }

  public MultiStringValue value(int j) { return value(new MultiStringValue(), j); }
  public MultiStringValue value(MultiStringValue obj, int j) { int o = __offset(4); return o != 0 ? obj.__init(__indirect(__vector(o) + j * 4), bb) : null; }
  public int valueLength() { int o = __offset(4); return o != 0 ? __vector_len(o) : 0; }

  public static int createMultiStringValueColumn(FlatBufferBuilder builder,
      int valueOffset) {
    builder.startObject(1);
    MultiStringValueColumn.addValue(builder, valueOffset);
    return MultiStringValueColumn.endMultiStringValueColumn(builder);
  }

  public static void startMultiStringValueColumn(FlatBufferBuilder builder) { builder.startObject(1); }
  public static void addValue(FlatBufferBuilder builder, int valueOffset) { builder.addOffset(0, valueOffset, 0); }
  public static int createValueVector(FlatBufferBuilder builder, int[] data) { builder.startVector(4, data.length, 4); for (int i = data.length - 1; i >= 0; i--) builder.addOffset(data[i]); return builder.endVector(); }
  public static void startValueVector(FlatBufferBuilder builder, int numElems) { builder.startVector(4, numElems, 4); }
  public static int endMultiStringValueColumn(FlatBufferBuilder builder) {
    int o = builder.endObject();
    return o;
  }
}

