// automatically generated by the FlatBuffers compiler, do not modify

package com.aliyun.igraph.client.proto.gremlin_fb;

import com.google.flatbuffers.FlatBufferBuilder;
import com.google.flatbuffers.Table;

import java.nio.ByteBuffer;
import java.nio.ByteOrder;

/**
 * @author alibaba
 */
@SuppressWarnings("unused")
public final class ObjectElement extends Table {
  public static ObjectElement getRootAsObjectElement(ByteBuffer _bb) { return getRootAsObjectElement(_bb, new ObjectElement()); }
  public static ObjectElement getRootAsObjectElement(ByteBuffer _bb, ObjectElement obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__init(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public ObjectElement __init(int _i, ByteBuffer _bb) { bb_pos = _i; bb = _bb; return this; }

  public long matchdocIndex() { int o = __offset(4); return o != 0 ? (long)bb.getInt(o + bb_pos) & 0xFFFFFFFFL : 0; }
  public long elementMetaId() { int o = __offset(6); return o != 0 ? bb.getLong(o + bb_pos) : 0; }
  public long elementType() { int o = __offset(8); return o != 0 ? (long)bb.getInt(o + bb_pos) & 0xFFFFFFFFL : 0; }

  public static int createObjectElement(FlatBufferBuilder builder,
      long matchdoc_index,
      long element_meta_id,
      long element_type) {
    builder.startObject(3);
    ObjectElement.addElementMetaId(builder, element_meta_id);
    ObjectElement.addElementType(builder, element_type);
    ObjectElement.addMatchdocIndex(builder, matchdoc_index);
    return ObjectElement.endObjectElement(builder);
  }

  public static void startObjectElement(FlatBufferBuilder builder) { builder.startObject(3); }
  public static void addMatchdocIndex(FlatBufferBuilder builder, long matchdocIndex) { builder.addInt(0, (int)matchdocIndex, 0); }
  public static void addElementMetaId(FlatBufferBuilder builder, long elementMetaId) { builder.addLong(1, elementMetaId, 0); }
  public static void addElementType(FlatBufferBuilder builder, long elementType) { builder.addInt(2, (int)elementType, 0); }
  public static int endObjectElement(FlatBufferBuilder builder) {
    int o = builder.endObject();
    return o;
  }
}

