// automatically generated by the FlatBuffers compiler, do not modify

package com.aliyun.igraph.client.proto.gremlin_fb;

import com.google.flatbuffers.FlatBufferBuilder;
import com.google.flatbuffers.Table;

import java.nio.ByteBuffer;
import java.nio.ByteOrder;

/**
 * @author alibaba
 */
@SuppressWarnings("unused")
public final class ObjectMap extends Table {
  public static ObjectMap getRootAsObjectMap(ByteBuffer _bb) { return getRootAsObjectMap(_bb, new ObjectMap()); }
  public static ObjectMap getRootAsObjectMap(ByteBuffer _bb, ObjectMap obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__init(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public ObjectMap __init(int _i, ByteBuffer _bb) { bb_pos = _i; bb = _bb; return this; }

  public ObjectVec keyObject() { return keyObject(new ObjectVec()); }
  public ObjectVec keyObject(ObjectVec obj) { int o = __offset(4); return o != 0 ? obj.__init(__indirect(o + bb_pos), bb) : null; }
  public ObjectVec valueObject() { return valueObject(new ObjectVec()); }
  public ObjectVec valueObject(ObjectVec obj) { int o = __offset(6); return o != 0 ? obj.__init(__indirect(o + bb_pos), bb) : null; }

  public static int createObjectMap(FlatBufferBuilder builder,
      int key_objectOffset,
      int value_objectOffset) {
    builder.startObject(2);
    ObjectMap.addValueObject(builder, value_objectOffset);
    ObjectMap.addKeyObject(builder, key_objectOffset);
    return ObjectMap.endObjectMap(builder);
  }

  public static void startObjectMap(FlatBufferBuilder builder) { builder.startObject(2); }
  public static void addKeyObject(FlatBufferBuilder builder, int keyObjectOffset) { builder.addOffset(0, keyObjectOffset, 0); }
  public static void addValueObject(FlatBufferBuilder builder, int valueObjectOffset) { builder.addOffset(1, valueObjectOffset, 0); }
  public static int endObjectMap(FlatBufferBuilder builder) {
    int o = builder.endObject();
    return o;
  }
}

