// automatically generated by the FlatBuffers compiler, do not modify

package com.aliyun.igraph.client.proto.gremlin_fb;

import com.google.flatbuffers.FlatBufferBuilder;
import com.google.flatbuffers.Table;

import java.nio.ByteBuffer;
import java.nio.ByteOrder;

/**
 * @author alibaba
 */
@SuppressWarnings("unused")
public final class ObjectMapEntry extends Table {
  public static ObjectMapEntry getRootAsObjectMapEntry(ByteBuffer _bb) { return getRootAsObjectMapEntry(_bb, new ObjectMapEntry()); }
  public static ObjectMapEntry getRootAsObjectMapEntry(ByteBuffer _bb, ObjectMapEntry obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__init(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public ObjectMapEntry __init(int _i, ByteBuffer _bb) { bb_pos = _i; bb = _bb; return this; }

  public GremlinObject keyObject() { return keyObject(new GremlinObject()); }
  public GremlinObject keyObject(GremlinObject obj) { int o = __offset(4); return o != 0 ? obj.__init(__indirect(o + bb_pos), bb) : null; }
  public GremlinObject valueObject() { return valueObject(new GremlinObject()); }
  public GremlinObject valueObject(GremlinObject obj) { int o = __offset(6); return o != 0 ? obj.__init(__indirect(o + bb_pos), bb) : null; }

  public static int createObjectMapEntry(FlatBufferBuilder builder,
      int key_objectOffset,
      int value_objectOffset) {
    builder.startObject(2);
    ObjectMapEntry.addValueObject(builder, value_objectOffset);
    ObjectMapEntry.addKeyObject(builder, key_objectOffset);
    return ObjectMapEntry.endObjectMapEntry(builder);
  }

  public static void startObjectMapEntry(FlatBufferBuilder builder) { builder.startObject(2); }
  public static void addKeyObject(FlatBufferBuilder builder, int keyObjectOffset) { builder.addOffset(0, keyObjectOffset, 0); }
  public static void addValueObject(FlatBufferBuilder builder, int valueObjectOffset) { builder.addOffset(1, valueObjectOffset, 0); }
  public static int endObjectMapEntry(FlatBufferBuilder builder) {
    int o = builder.endObject();
    return o;
  }
}

