// automatically generated by the FlatBuffers compiler, do not modify

package com.aliyun.igraph.client.proto.gremlin_fb;

import com.google.flatbuffers.FlatBufferBuilder;
import com.google.flatbuffers.Table;

import java.nio.ByteBuffer;
import java.nio.ByteOrder;

/**
 * @author alibaba
 */
@SuppressWarnings("unused")
public final class ObjectSet extends Table {
  public static ObjectSet getRootAsObjectSet(ByteBuffer _bb) { return getRootAsObjectSet(_bb, new ObjectSet()); }
  public static ObjectSet getRootAsObjectSet(ByteBuffer _bb, ObjectSet obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__init(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public ObjectSet __init(int _i, ByteBuffer _bb) { bb_pos = _i; bb = _bb; return this; }

  public ObjectVec object() { return object(new ObjectVec()); }
  public ObjectVec object(ObjectVec obj) { int o = __offset(4); return o != 0 ? obj.__init(__indirect(o + bb_pos), bb) : null; }

  public static int createObjectSet(FlatBufferBuilder builder,
      int objectOffset) {
    builder.startObject(1);
    ObjectSet.addObject(builder, objectOffset);
    return ObjectSet.endObjectSet(builder);
  }

  public static void startObjectSet(FlatBufferBuilder builder) { builder.startObject(1); }
  public static void addObject(FlatBufferBuilder builder, int objectOffset) { builder.addOffset(0, objectOffset, 0); }
  public static int endObjectSet(FlatBufferBuilder builder) {
    int o = builder.endObject();
    return o;
  }
}

