// automatically generated by the FlatBuffers compiler, do not modify

package com.aliyun.igraph.client.proto.gremlin_fb;

import com.google.flatbuffers.FlatBufferBuilder;
import com.google.flatbuffers.Table;

import java.nio.ByteBuffer;
import java.nio.ByteOrder;

/**
 * @author alibaba
 */
@SuppressWarnings("unused")
public final class ObjectVec extends Table {
  public static ObjectVec getRootAsObjectVec(ByteBuffer _bb) { return getRootAsObjectVec(_bb, new ObjectVec()); }
  public static ObjectVec getRootAsObjectVec(ByteBuffer _bb, ObjectVec obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__init(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public ObjectVec __init(int _i, ByteBuffer _bb) { bb_pos = _i; bb = _bb; return this; }

  public byte valueType() { int o = __offset(4); return o != 0 ? bb.get(o + bb_pos) : 0; }
  public Table value(Table obj) { int o = __offset(6); return o != 0 ? __union(obj, o) : null; }

  public static int createObjectVec(FlatBufferBuilder builder,
      byte value_type,
      int valueOffset) {
    builder.startObject(2);
    ObjectVec.addValue(builder, valueOffset);
    ObjectVec.addValueType(builder, value_type);
    return ObjectVec.endObjectVec(builder);
  }

  public static void startObjectVec(FlatBufferBuilder builder) { builder.startObject(2); }
  public static void addValueType(FlatBufferBuilder builder, byte valueType) { builder.addByte(0, valueType, 0); }
  public static void addValue(FlatBufferBuilder builder, int valueOffset) { builder.addOffset(1, valueOffset, 0); }
  public static int endObjectVec(FlatBufferBuilder builder) {
    int o = builder.endObject();
    return o;
  }
}

