// automatically generated by the FlatBuffers compiler, do not modify

package com.aliyun.igraph.client.proto.gremlin_fb;

import com.google.flatbuffers.FlatBufferBuilder;
import com.google.flatbuffers.Table;

import java.nio.ByteBuffer;
import java.nio.ByteOrder;

/**
 * @author alibaba
 */
@SuppressWarnings("unused")
public final class ObjectVecByRow extends Table {
  public static ObjectVecByRow getRootAsObjectVecByRow(ByteBuffer _bb) { return getRootAsObjectVecByRow(_bb, new ObjectVecByRow()); }
  public static ObjectVecByRow getRootAsObjectVecByRow(ByteBuffer _bb, ObjectVecByRow obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__init(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public ObjectVecByRow __init(int _i, ByteBuffer _bb) { bb_pos = _i; bb = _bb; return this; }

  public GremlinObject object(int j) { return object(new GremlinObject(), j); }
  public GremlinObject object(GremlinObject obj, int j) { int o = __offset(4); return o != 0 ? obj.__init(__indirect(__vector(o) + j * 4), bb) : null; }
  public int objectLength() { int o = __offset(4); return o != 0 ? __vector_len(o) : 0; }

  public static int createObjectVecByRow(FlatBufferBuilder builder,
      int objectOffset) {
    builder.startObject(1);
    ObjectVecByRow.addObject(builder, objectOffset);
    return ObjectVecByRow.endObjectVecByRow(builder);
  }

  public static void startObjectVecByRow(FlatBufferBuilder builder) { builder.startObject(1); }
  public static void addObject(FlatBufferBuilder builder, int objectOffset) { builder.addOffset(0, objectOffset, 0); }
  public static int createObjectVector(FlatBufferBuilder builder, int[] data) { builder.startVector(4, data.length, 4); for (int i = data.length - 1; i >= 0; i--) builder.addOffset(data[i]); return builder.endVector(); }
  public static void startObjectVector(FlatBufferBuilder builder, int numElems) { builder.startVector(4, numElems, 4); }
  public static int endObjectVecByRow(FlatBufferBuilder builder) {
    int o = builder.endObject();
    return o;
  }
}

