// automatically generated by the FlatBuffers compiler, do not modify

package com.aliyun.igraph.client.proto.gremlin_fb;

import com.google.flatbuffers.FlatBufferBuilder;
import com.google.flatbuffers.Table;

import java.nio.ByteBuffer;
import java.nio.ByteOrder;

/**
 * @author alibaba
 */
@SuppressWarnings("unused")
public final class UInt16Value extends Table {
  public static UInt16Value getRootAsUInt16Value(ByteBuffer _bb) { return getRootAsUInt16Value(_bb, new UInt16Value()); }
  public static UInt16Value getRootAsUInt16Value(ByteBuffer _bb, UInt16Value obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__init(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public UInt16Value __init(int _i, ByteBuffer _bb) { bb_pos = _i; bb = _bb; return this; }

  public int value() { int o = __offset(4); return o != 0 ? bb.getShort(o + bb_pos) & 0xFFFF : 0; }

  public static int createUInt16Value(FlatBufferBuilder builder,
      int value) {
    builder.startObject(1);
    UInt16Value.addValue(builder, value);
    return UInt16Value.endUInt16Value(builder);
  }

  public static void startUInt16Value(FlatBufferBuilder builder) { builder.startObject(1); }
  public static void addValue(FlatBufferBuilder builder, int value) { builder.addShort(0, (short)value, 0); }
  public static int endUInt16Value(FlatBufferBuilder builder) {
    int o = builder.endObject();
    return o;
  }
}

