// automatically generated by the FlatBuffers compiler, do not modify

package com.aliyun.igraph.client.proto.gremlin_fb;

import com.google.flatbuffers.FlatBufferBuilder;
import com.google.flatbuffers.Table;

import java.nio.ByteBuffer;
import java.nio.ByteOrder;

/**
 * @author alibaba
 */
@SuppressWarnings("unused")
public final class UInt8Value extends Table {
  public static UInt8Value getRootAsUInt8Value(ByteBuffer _bb) { return getRootAsUInt8Value(_bb, new UInt8Value()); }
  public static UInt8Value getRootAsUInt8Value(ByteBuffer _bb, UInt8Value obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__init(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public UInt8Value __init(int _i, ByteBuffer _bb) { bb_pos = _i; bb = _bb; return this; }

  public int value() { int o = __offset(4); return o != 0 ? bb.get(o + bb_pos) & 0xFF : 0; }

  public static int createUInt8Value(FlatBufferBuilder builder,
      int value) {
    builder.startObject(1);
    UInt8Value.addValue(builder, value);
    return UInt8Value.endUInt8Value(builder);
  }

  public static void startUInt8Value(FlatBufferBuilder builder) { builder.startObject(1); }
  public static void addValue(FlatBufferBuilder builder, int value) { builder.addByte(0, (byte)value, 0); }
  public static int endUInt8Value(FlatBufferBuilder builder) {
    int o = builder.endObject();
    return o;
  }
}

