// automatically generated by the FlatBuffers compiler, do not modify

package com.aliyun.igraph.client.proto.gremlin_fb;

import com.google.flatbuffers.FlatBufferBuilder;
import com.google.flatbuffers.Table;

import java.nio.ByteBuffer;
import java.nio.ByteOrder;

/**
 * @author alibaba
 */
@SuppressWarnings("unused")
public final class UInt32Value extends Table {
  public static UInt32Value getRootAsUInt32Value(ByteBuffer _bb) { return getRootAsUInt32Value(_bb, new UInt32Value()); }
  public static UInt32Value getRootAsUInt32Value(ByteBuffer _bb, UInt32Value obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__init(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public UInt32Value __init(int _i, ByteBuffer _bb) { bb_pos = _i; bb = _bb; return this; }

  public long value() { int o = __offset(4); return o != 0 ? (long)bb.getInt(o + bb_pos) & 0xFFFFFFFFL : 0; }

  public static int createUInt32Value(FlatBufferBuilder builder,
      long value) {
    builder.startObject(1);
    UInt32Value.addValue(builder, value);
    return UInt32Value.endUInt32Value(builder);
  }

  public static void startUInt32Value(FlatBufferBuilder builder) { builder.startObject(1); }
  public static void addValue(FlatBufferBuilder builder, long value) { builder.addInt(0, (int)value, 0); }
  public static int endUInt32Value(FlatBufferBuilder builder) {
    int o = builder.endObject();
    return o;
  }
}

