// automatically generated by the FlatBuffers compiler, do not modify

package com.aliyun.igraph.client.proto.gremlin_fb;

import com.google.flatbuffers.FlatBufferBuilder;
import com.google.flatbuffers.Table;

import java.nio.ByteBuffer;
import java.nio.ByteOrder;

/**
 * @author alibaba
 */
@SuppressWarnings("unused")
public final class UInt64Value extends Table {
  public static UInt64Value getRootAsUInt64Value(ByteBuffer _bb) { return getRootAsUInt64Value(_bb, new UInt64Value()); }
  public static UInt64Value getRootAsUInt64Value(ByteBuffer _bb, UInt64Value obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__init(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public UInt64Value __init(int _i, ByteBuffer _bb) { bb_pos = _i; bb = _bb; return this; }

  public long value() { int o = __offset(4); return o != 0 ? bb.getLong(o + bb_pos) : 0; }

  public static int createUInt64Value(FlatBufferBuilder builder,
      long value) {
    builder.startObject(1);
    UInt64Value.addValue(builder, value);
    return UInt64Value.endUInt64Value(builder);
  }

  public static void startUInt64Value(FlatBufferBuilder builder) { builder.startObject(1); }
  public static void addValue(FlatBufferBuilder builder, long value) { builder.addLong(0, value, 0); }
  public static int endUInt64Value(FlatBufferBuilder builder) {
    int o = builder.endObject();
    return o;
  }
}

